'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import JSZip from 'jszip';

interface SetupConfig {
    webhookSecret: string;
    apiKey: string;
    tier: string;
    pilotMode: boolean;
    processor: string;
}

export default function GenerateSetupPage() {
    const [config, setConfig] = useState<SetupConfig | null>(null);
    const [generated, setGenerated] = useState(false);
    const [copied, setCopied] = useState(false);
    const [copiedInstall, setCopiedInstall] = useState(false);
    const [hydrated, setHydrated] = useState(false);
    const [showFallback, setShowFallback] = useState(false);
    const [downloadingZip, setDownloadingZip] = useState(false);
    const router = useRouter();

    useEffect(() => {
        // Set hydrated first to indicate client render
        setHydrated(true);

        try {
            const webhookSecret = sessionStorage.getItem('setup_webhook_secret');
            const apiKey = sessionStorage.getItem('setup_api_key') || '';

            // Non-sensitive state: try sessionStorage first, fallback to localStorage
            const tier = sessionStorage.getItem('setup_tier') ||
                localStorage.getItem('setup_tier') ||
                'tier1';
            const pilotMode = (sessionStorage.getItem('setup_pilot_mode') ||
                localStorage.getItem('setup_pilot_mode')) === 'true';
            const processor = sessionStorage.getItem('payflux_setup_processor') ||
                localStorage.getItem('payflux_setup_processor') ||
                'stripe';

            if (!webhookSecret) {
                router.push('/setup/connect');
                return;
            }

            setConfig({ webhookSecret, apiKey, tier, pilotMode, processor });
        } catch (error) {
            // SessionStorage/localStorage blocked or unavailable (Safari private mode, etc.)
            router.push('/setup/connect');
        }
    }, [router]);

    useEffect(() => {
        const timer = setTimeout(() => {
            if (!config) {
                setShowFallback(true);
            }
        }, 2000);
        return () => clearTimeout(timer);
    }, [config]);

    const generateEnvFile = () => {
        if (!config) return '';

        const isGenericWebhook = config.processor === 'generic_webhook';

        return `# Generated by PayFlux Dashboard
# Store securely. Do not commit.
# Generated: ${new Date().toISOString()}

# PayFlux Core
PAYFLUX_API_KEY=your-secure-api-key-here
PAYFLUX_TIER=${config.tier}
PAYFLUX_PILOT_MODE=${config.pilotMode}

${isGenericWebhook ? `# Processor Configuration
# Note: Core currently reads STRIPE_WEBHOOK_SECRET for webhook auth (all processors).
# PAYFLUX_PROCESSOR and PAYFLUX_WEBHOOK_SECRET are for clarity and future compatibility.
PAYFLUX_PROCESSOR=generic_webhook
PAYFLUX_WEBHOOK_SECRET=${config.webhookSecret}
STRIPE_WEBHOOK_SECRET=${config.webhookSecret}` : `# Stripe Integration
STRIPE_API_KEY=${config.apiKey || 'your-stripe-api-key'}
STRIPE_WEBHOOK_SECRET=${config.webhookSecret}`}

# Redis (default local)
REDIS_ADDR=redis:6379

# Server
HTTP_ADDR=:8080

# Kill Switches (all enabled by default)
PAYFLUX_INGEST_ENABLED=true
PAYFLUX_WARNINGS_ENABLED=true
PAYFLUX_TIER2_ENABLED=${config.tier === 'tier2'}

# Rate Limits
PAYFLUX_INGEST_RPS=100
PAYFLUX_INGEST_BURST=500
`;
    };

    const generateDockerCompose = () => {
        return `# Generated by PayFlux Dashboard
# Run with: docker compose up -d

services:
  payflux:
    image: ghcr.io/blight-east/payflux:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
`;
    };

    const generateReadme = () => {
        return `# PayFlux Quick Start

## Prerequisites
- Docker and Docker Compose installed
- Stripe webhook endpoint configured to: \`https://your-domain/v1/events/payment_exhaust\`

## Setup
1. Save the \`.env\` file in your project directory
2. Save the \`docker-compose.yml\` file in the same directory
3. Run:
   \`\`\`bash
   docker compose up -d
   \`\`\`

## Verify
Check health: \`curl http://localhost:8080/health\`

## Configuration
- **Tier**: ${config?.tier === 'tier2' ? 'Tier 2 (Interpretation + Alerts)' : 'Tier 1 (Detection Only)'}
- **Pilot Mode**: ${config?.pilotMode ? 'Enabled' : 'Disabled'}

## Support
See full documentation at https://payflux.dev/docs
`;
    };

    const downloadFile = (content: string, filename: string) => {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleGenerate = () => {
        setGenerated(true);
    };

    const handleDownloadAll = () => {
        downloadFile(generateEnvFile(), '.env');
        setTimeout(() => downloadFile(generateDockerCompose(), 'docker-compose.yml'), 100);
        setTimeout(() => downloadFile(generateReadme(), 'README.md'), 200);
    };

    const handleDownloadZip = async () => {
        if (downloadingZip) return;
        setDownloadingZip(true);

        try {
            const zip = new JSZip();
            zip.file('.env', generateEnvFile());
            zip.file('docker-compose.yml', generateDockerCompose());
            zip.file('README.md', generateReadme());

            const blob = await zip.generateAsync({ type: 'blob' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'payflux-setup.zip';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        } finally {
            setDownloadingZip(false);
        }
    };

    const handleCopyCommand = () => {
        navigator.clipboard.writeText('docker compose up -d');
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleCopyInstallCommands = () => {
        const commands = 'unzip payflux-setup.zip -d payflux-setup && cd payflux-setup && docker compose up -d';

        if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(commands).then(
                () => {
                    setCopiedInstall(true);
                    setTimeout(() => setCopiedInstall(false), 2000);
                },
                () => {
                    // Fallback for clipboard write failure
                    const textarea = document.createElement('textarea');
                    textarea.value = commands;
                    textarea.style.position = 'fixed';
                    textarea.style.opacity = '0';
                    document.body.appendChild(textarea);
                    textarea.select();
                    try {
                        document.execCommand('copy');
                        setCopiedInstall(true);
                        setTimeout(() => setCopiedInstall(false), 2000);
                    } catch (err) {
                        // Silent failure
                    }
                    document.body.removeChild(textarea);
                }
            );
        } else {
            // Fallback for browsers without clipboard API
            const textarea = document.createElement('textarea');
            textarea.value = commands;
            textarea.style.position = 'fixed';
            textarea.style.opacity = '0';
            document.body.appendChild(textarea);
            textarea.select();
            try {
                document.execCommand('copy');
                setCopiedInstall(true);
                setTimeout(() => setCopiedInstall(false), 2000);
            } catch (err) {
                // Silent failure
            }
            document.body.removeChild(textarea);
        }
    };

    const handleFinish = () => {
        // Clear session storage
        sessionStorage.removeItem('setup_webhook_secret');
        sessionStorage.removeItem('setup_api_key');
        sessionStorage.removeItem('setup_tier');
        sessionStorage.removeItem('setup_pilot_mode');
        router.push('/dashboard');
    };

    if (!hydrated || !config) {
        if (showFallback) {
            return (
                <div className="p-8 max-w-3xl mx-auto">
                    <div className="mb-8">
                        <h2 className="text-2xl font-bold text-white tracking-tight">Setup State Missing</h2>
                        <p className="text-zinc-500 text-sm mt-2">
                            Your setup configuration could not be loaded. This may happen if your session expired or browser storage was cleared.
                        </p>
                        <button
                            onClick={() => router.push('/setup/connect')}
                            className="mt-6 px-6 py-2.5 bg-white text-black font-bold rounded text-sm hover:bg-zinc-200 transition-colors"
                        >
                            Back to Connect
                        </button>
                    </div>
                </div>
            );
        }

        return (
            <div className="p-8 max-w-3xl mx-auto">
                <div className="mb-8">
                    <div className="flex items-center space-x-2 text-[10px] text-zinc-500 uppercase tracking-widest mb-4">
                        <span className="text-zinc-600">Step 1</span>
                        <span>→</span>
                        <span className="text-zinc-600">Step 2</span>
                        <span>→</span>
                        <span className="text-blue-400">Step 3</span>
                        <span>→</span>
                        <span>Generate Setup</span>
                    </div>
                    <h2 className="text-2xl font-bold text-white tracking-tight">Generate Your Setup</h2>
                    <p className="text-zinc-500 text-sm mt-1">Loading configuration...</p>
                </div>
            </div>
        );
    }

    return (
        <div className="p-8 max-w-3xl mx-auto">
            <div className="mb-8">
                <div className="flex items-center space-x-2 text-[10px] text-zinc-500 uppercase tracking-widest mb-4">
                    <span className="text-zinc-600">Step 1</span>
                    <span>→</span>
                    <span className="text-zinc-600">Step 2</span>
                    <span>→</span>
                    <span className="text-blue-400">Step 3</span>
                    <span>→</span>
                    <span>Generate Setup</span>
                </div>
                <h2 className="text-2xl font-bold text-white tracking-tight">Generate Your Setup</h2>
                <p className="text-zinc-500 text-sm mt-1">Download your configuration files and run one command.</p>
            </div>

            {/* Config Summary */}
            <div className="bg-zinc-950 border border-zinc-800 rounded-lg p-6 mb-6">
                <h3 className="text-sm font-bold text-white uppercase tracking-widest mb-4">Configuration Summary</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                        <span className="text-zinc-500">Processor:</span>
                        <span className="ml-2 text-white">{config.processor === 'generic_webhook' ? 'Generic Webhook' : 'Stripe'}</span>
                    </div>
                    <div>
                        <span className="text-zinc-500">Tier:</span>
                        <span className="ml-2 text-white capitalize">{config.tier === 'tier2' ? 'Tier 2' : 'Tier 1'}</span>
                    </div>
                    <div>
                        <span className="text-zinc-500">Pilot Mode:</span>
                        <span className={`ml-2 ${config.pilotMode ? 'text-green-500' : 'text-zinc-400'}`}>
                            {config.pilotMode ? 'Enabled' : 'Disabled'}
                        </span>
                    </div>
                    <div>
                        <span className="text-zinc-500">Webhook Secret:</span>
                        <span className="ml-2 text-white font-mono text-xs">whsec_***...{config.webhookSecret.slice(-4)}</span>
                    </div>
                </div>
            </div>

            {!generated ? (
                <div className="text-center py-12">
                    <button
                        onClick={handleGenerate}
                        className="px-8 py-4 bg-white text-black font-bold rounded-lg text-lg hover:bg-zinc-200 transition-colors"
                    >
                        Generate Setup Files
                    </button>
                    <p className="mt-4 text-xs text-zinc-600">
                        This will prepare your .env, docker-compose.yml, and README.md files
                    </p>
                </div>
            ) : (
                <div className="space-y-6">
                    {/* Generated Files */}
                    <div className="bg-zinc-950 border border-zinc-800 rounded-lg overflow-hidden">
                        <div className="flex items-center justify-between p-4 border-b border-zinc-800">
                            <h4 className="text-sm font-bold text-white">.env</h4>
                            <button
                                onClick={() => downloadFile(generateEnvFile(), '.env')}
                                className="text-xs text-blue-400 hover:text-blue-300"
                            >
                                Download
                            </button>
                        </div>
                        <pre className="p-4 text-xs text-zinc-400 overflow-x-auto max-h-48 bg-black">
                            {generateEnvFile()}
                        </pre>
                    </div>

                    <div className="bg-zinc-950 border border-zinc-800 rounded-lg overflow-hidden">
                        <div className="flex items-center justify-between p-4 border-b border-zinc-800">
                            <h4 className="text-sm font-bold text-white">docker-compose.yml</h4>
                            <button
                                onClick={() => downloadFile(generateDockerCompose(), 'docker-compose.yml')}
                                className="text-xs text-blue-400 hover:text-blue-300"
                            >
                                Download
                            </button>
                        </div>
                        <pre className="p-4 text-xs text-zinc-400 overflow-x-auto max-h-48 bg-black">
                            {generateDockerCompose()}
                        </pre>
                    </div>

                    {/* Before You Start */}
                    <div className="bg-zinc-900/30 border border-zinc-800 rounded-lg p-6">
                        <h4 className="text-sm font-medium text-zinc-300 mb-3">Before you start</h4>
                        <p className="text-sm text-zinc-500 mb-4">
                            PayFlux runs as a secure container on your infrastructure.<br />
                            You'll need Docker Desktop installed.
                        </p>
                        <ul className="text-sm text-zinc-500 space-y-1.5">
                            <li>
                                • Mac / Windows:{' '}
                                <a
                                    href="https://www.docker.com/get-started"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-zinc-400 hover:text-white underline underline-offset-2"
                                >
                                    Install Docker Desktop
                                </a>
                            </li>
                            <li>
                                • Linux:{' '}
                                <a
                                    href="https://docs.docker.com/engine/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-zinc-400 hover:text-white underline underline-offset-2"
                                >
                                    Install Docker Engine
                                </a>
                            </li>
                        </ul>
                        <p className="text-sm text-zinc-600 mt-4">
                            Once Docker is installed, onboarding is a single command.
                        </p>
                    </div>

                    {/* Run Command */}
                    <div className="bg-green-500/5 border border-green-500/20 rounded-lg p-6">
                        <h4 className="text-sm font-bold text-green-500 uppercase tracking-widest mb-3">Run Command</h4>
                        <div className="flex items-center space-x-3">
                            <code className="flex-1 bg-black border border-zinc-800 rounded px-4 py-3 text-green-400 font-mono text-sm">
                                docker compose up -d
                            </code>
                            <button
                                onClick={handleCopyCommand}
                                className={`px-4 py-3 text-xs font-medium rounded transition-all ${copied
                                    ? 'bg-green-600 text-white'
                                    : 'bg-zinc-900 text-zinc-400 hover:text-white'
                                    }`}
                            >
                                {copied ? 'Copied!' : 'Copy'}
                            </button>
                        </div>
                        <p className="mt-3 text-xs text-zinc-500">
                            Run this command in the directory where you saved the files above.
                        </p>
                    </div>

                    {/* What to Expect Next */}
                    <div className="bg-zinc-900/30 border border-zinc-800 rounded-lg p-6">
                        <h4 className="text-sm font-medium text-zinc-300 mb-4">What to expect next</h4>
                        <ul className="space-y-2.5 text-sm text-zinc-500">
                            <li>
                                • Health check available at{' '}
                                <code className="text-xs bg-black px-1.5 py-0.5 rounded text-zinc-400">http://localhost:8080/health</code>
                            </li>
                            <li>• Warnings appear in the PayFlux dashboard (Tier 2 / Pilot only)</li>
                            <li>• No traffic is blocked — PayFlux observes and reports only</li>
                            <li>
                                • You can shut it down anytime with{' '}
                                <code className="text-xs bg-black px-1.5 py-0.5 rounded text-zinc-400">docker compose down</code>
                            </li>
                        </ul>
                        <p className="mt-4 text-[10px] text-zinc-600 italic">
                            PayFlux surfaces operational context; it does not block payments.
                        </p>
                    </div>

                    {/* Download ZIP - Primary Option */}
                    <div className="bg-zinc-950 border border-zinc-800 rounded-lg p-6 mb-4">
                        <button
                            onClick={handleDownloadZip}
                            disabled={!config || downloadingZip}
                            className="w-full px-6 py-3 bg-white text-black font-bold rounded text-sm hover:bg-zinc-200 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {downloadingZip ? 'Generating...' : 'Download ZIP'}
                        </button>
                        <p className="mt-2 text-xs text-zinc-500 text-center">
                            Use this if you want one file to download, unzip, and run.
                        </p>

                        <button
                            onClick={handleCopyInstallCommands}
                            disabled={!config}
                            className="mt-3 w-full px-6 py-2.5 bg-zinc-900 text-white font-bold rounded text-sm hover:bg-zinc-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {copiedInstall ? 'Copied!' : 'Copy install commands'}
                        </button>
                        <p className="mt-2 text-xs text-zinc-500 text-center">
                            Copies the commands to unzip, cd, and start PayFlux with Docker.
                        </p>
                    </div>

                    {/* Download All */}
                    <div className="flex justify-between items-center pt-4">
                        <button
                            onClick={handleDownloadAll}
                            className="px-6 py-2.5 bg-zinc-900 text-white font-bold rounded text-sm hover:bg-zinc-800 transition-colors"
                        >
                            Download All Files
                        </button>
                        <button
                            onClick={handleFinish}
                            className="px-6 py-2.5 bg-white text-black font-bold rounded text-sm hover:bg-zinc-200 transition-colors"
                        >
                            Finish Setup →
                        </button>
                    </div>
                </div>
            )
            }

            {/* Security Notice */}
            <div className="mt-8 bg-zinc-900/50 border border-zinc-800 rounded p-4">
                <h4 className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-2">Security Reminder</h4>
                <ul className="text-[10px] text-zinc-500 space-y-1">
                    <li>• Your secrets are processed in-browser only and never sent to our servers</li>
                    <li>• The .env file contains sensitive data — do not commit it to version control</li>
                    <li>• Change PAYFLUX_API_KEY to a strong, unique value before deploying</li>
                </ul>
            </div>
        </div >
    );
}
